apiVersion: v1
kind: ConfigMap
metadata:
  name: wg0-conf
  namespace: vpn
  labels:
    app: wireguard
data:
  wg0.conf: |
    [Interface]
    # PublicKey XZlb2mNUM+LahKF6tC6TEbGnBBimft1AIIsB0ot4ziE=
    Address = 10.1.30.1/24,fdb0:5dfe:70d8:7f0b::1/48
    ListenPort = 51820
    PostUp = wg set %i private-key /etc/wireguard/wg0.key
    PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; ip6tables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    MTU = 1500
    SaveConfig = false

    [Peer]
    # Pixel4a
    PublicKey = jOqn6h664lvnKn9EDzytDAYSVfTtE4KP/V1mHSF7dn8=
    AllowedIPs = 10.1.30.4/32,fdb0:5dfe:70d8:7f0b::4/128

    [Peer]
    # MacBook M.
    PublicKey = JIK3nSmGIOJR2ZqYtguBj1Ev0+WNiOjfFUBXKWZc+00=
    AllowedIPs = 10.1.30.5/32,fdb0:5dfe:70d8:7f0b::5/128

    [Peer]
    # edgerouter-x
    PublicKey = WqMz2MI032ucMsN16f0IZHF4iHyRLtXIz0liX8uezng=
    AllowedIPs = 10.1.30.10/32,fdb0:5dfe:70d8:7f0b::10/128
    AllowedIPs = 192.168.10.1/24,2a02:168:f77a:42::1/64

    [Peer]
    # SI-553-SHL-MAC
    PublicKey = 2aMonMuftj1Z2uNSyRNiSGljATbX4925HEr5s/uOmwQ=
    AllowedIPs = 10.1.30.11/32,fdb0:5dfe:70d8:7f0b::11/128
