apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nzbget
  namespace: plex
  labels:
    app.kubernetes.io/name: nzbget
    app.kubernetes.io/instance: nzbget
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nzbget
      app.kubernetes.io/instance: nzbget
  serviceName: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nzbget
        app.kubernetes.io/instance: nzbget
    spec:
      containers:
        - name: gatekeeper
          image: quay.io/keycloak/keycloak-gatekeeper:10.0.0
          imagePullPolicy: IfNotPresent
          args:
          - --listen=:3000
          - --discovery-url=https://sso.srueg.ch/auth/realms/lab
          - --client-id=nzbget
          - --upstream-url=http://localhost:6789
          - --resources
          - "uri=/*|roles=nzbget:login"
          - --enable-encrypted-token
          - --force-encrypted-cookie
          - --enable-logging
          - --enable-refresh-tokens
          env:
          - name: PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: nzbget-gatekeeper
                key: client-secret
          - name: PROXY_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: nzbget-gatekeeper
                key: encryption-key
          ports:
          - name: http
            containerPort: 3000
          livenessProbe:
            httpGet:
              path: /oauth/health
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /oauth/health
              port: http
        - name: nzbget
          image: docker.io/linuxserver/nzbget:v21.1-r2311-ls4
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "10001"
            - name: PGID
              value: "10001"
            - name: TZ
              value: "Europe/Zurich"
          volumeMounts:
            - mountPath: /config/
              name: config
            - mountPath: /downloads/
              name: downloads
              subPath: addons/nzbget/
            - mountPath: /intermediate/
              name: intermediate
          ports:
            - name: nzbget
              containerPort: 6789
          livenessProbe:
            httpGet:
              path: /
              port: nzbget
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: nzbget
      terminationGracePeriodSeconds: 60
      volumes:
        - name: intermediate
          persistentVolumeClaim:
            claimName: nzbget-downloads
        - name: downloads
          persistentVolumeClaim:
            claimName: plex-data
        - name: config
          persistentVolumeClaim:
            claimName: nzbget-config
