apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vivanina-demo-postgresql
  namespace: argocd
spec:
  destination:
    namespace: vivanina-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: '*'
    helm:
      values: |
        postgresqlDatabase: vivanina-demo
        existingSecret: vivanina
        persistence:
          existingClaim: postgresql
