apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tautulli
  namespace: plex
  labels:
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/instance: tautulli
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli
      app.kubernetes.io/instance: tautulli
  serviceName: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tautulli
        app.kubernetes.io/instance: tautulli
    spec:
      containers:
        - name: oauth-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1@sha256:791aef35b8d1d2a325028b188d5a650605d69985a0dab1233c06079e7321eee0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 4180
            name: http
          args:
          - --http-address=:4180
          - --https-address=
          - --provider=keycloak
          - --keycloak-group=/admin
          - --email-domain=*
          - --scope=openid profile email
          - --login-url=https://sso.srueg.ch/auth/realms/lab/protocol/openid-connect/auth
          - --redeem-url=https://sso.srueg.ch/auth/realms/lab/protocol/openid-connect/token
          - --validate-url=https://sso.srueg.ch/auth/realms/lab/protocol/openid-connect/userinfo
          - --upstream=http://localhost:8181
          - --reverse-proxy
          - --silence-ping-logging
          - --cookie-expire=1h
          - --skip-provider-button
          env:
          - name: OAUTH2_PROXY_CLIENT_ID
            value: tautulli
          - name: OAUTH2_PROXY_COOKIE_SAMESITE
            value: lax
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: tautulli-oauth
                key: client-secret
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: tautulli-oauth
                key: cookie-secret
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
        - name: tautulli
          image: docker.io/linuxserver/tautulli:v2.7.0-ls6@sha256:f3dc71947d5aca47b561f755d08fdf9ff024725f7b4991a164b34a86f07e222e
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "10001"
            - name: PGID
              value: "10001"
            - name: TZ
              value: "Europe/Zurich"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: plex-logs
              mountPath: /logs
              subPath: Library/Application Support/Plex Media Server/Logs
          ports:
            - name: tautulli
              containerPort: 8181
          readinessProbe:
            httpGet:
              path: /welcome
              port: tautulli
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: tautulli-config
        - name: plex-logs
          persistentVolumeClaim:
            claimName: plex-config
