apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  destination:
    namespace: ingress-controller
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: '*'
    helm:
      values: |
        controller:
          kind: DaemonSet
          hostNetwork: true
          service:
            enabled: false
          dnsPolicy: ClusterFirstWithHostNet
          extraArgs:
            default-ssl-certificate: ingress-controller/srueg-ch-wildcard-tls
        podSecurityPolicy:
          enabled: false
