apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: srueg-ch-wildcard
  namespace: ingress-controller
spec:
  secretName: srueg-ch-wildcard-tls
  issuerRef:
    name: letsencrypt-production
  commonName: "*.srueg.ch"
  dnsNames:
  - "*.srueg.ch"
  keyAlgorithm: ecdsa
