apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: srueg-ch-wildcard
  namespace: ingress-controller
spec:
  secretName: srueg-ch-wildcard-tls
  issuerRef:
    name: letsencrypt-production
  dnsNames:
  - "*.srueg.ch"
  privateKey:
    algorithm: ecdsa
