apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
  namespace: plex
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
      app.kubernetes.io/instance: radarr
  serviceName: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
        app.kubernetes.io/instance: radarr
    spec:
      containers:
        - name: gatekeeper
          image: quay.io/keycloak/keycloak-gatekeeper:10.0.0
          imagePullPolicy: IfNotPresent
          args:
          - --listen=:3000
          - --discovery-url=https://sso.srueg.ch/auth/realms/lab
          - --client-id=radarr
          - --upstream-url=http://localhost:7878
          - --resources
          - "uri=/*|roles=radarr:login"
          - --resources
          - uri=/api/*|white-listed=true
          - --enable-encrypted-token
          - --force-encrypted-cookie
          - --enable-logging
          - --enable-refresh-tokens
          env:
          - name: PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: radarr-gatekeeper
                key: client-secret
          - name: PROXY_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: radarr-gatekeeper
                key: encryption-key
          ports:
          - name: http
            containerPort: 3000
          livenessProbe:
            httpGet:
              path: /oauth/health
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /oauth/health
              port: http
        - name: radarr
          image: "docker.io/linuxserver/radarr:v0.2.0.1480-ls59"
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "10001"
            - name: PGID
              value: "10001"
            - name: TZ
              value: "Europe/Zurich"
          volumeMounts:
            - mountPath: /config/
              name: config
            - mountPath: /addons/
              name: plex
              subPath: addons/
            - mountPath: /movies/
              name: plex
              subPath: Movies/
          ports:
            - name: radarr
              containerPort: 7878
          livenessProbe:
            httpGet:
              path: /login
              port: radarr
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /login
              port: radarr
      terminationGracePeriodSeconds: 60
      volumes:
        - name: plex
          persistentVolumeClaim:
            claimName: plex-data
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
