apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
  namespace: plex
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
      app.kubernetes.io/instance: radarr
  serviceName: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
        app.kubernetes.io/instance: radarr
    spec:
      containers:
        - name: oauth-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 4180
            name: http
          args:
          - --http-address=:4180
          - --https-address=
          - --provider=keycloak
          - --keycloak-group=/admin
          - --email-domain=*
          - --scope=openid profile email
          - --login-url=https://sso.srueg.ch/auth/realms/lab/protocol/openid-connect/auth
          - --redeem-url=https://sso.srueg.ch/auth/realms/lab/protocol/openid-connect/token
          - --validate-url=https://sso.srueg.ch/auth/realms/lab/protocol/openid-connect/userinfo
          - --upstream=http://localhost:6789
          - --reverse-proxy
          - --silence-ping-logging
          - --cookie-expire=1h
          env:
          - name: OAUTH2_PROXY_CLIENT_ID
            value: radarr
          - name: OAUTH2_PROXY_COOKIE_SAMESITE
            value: lax
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: radarr-oauth
                key: client-secret
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: radarr-oauth
                key: cookie-secret
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
        - name: radarr
          image: docker.io/linuxserver/radarr:0.2.0.1540-ls21
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "10001"
            - name: PGID
              value: "10001"
            - name: TZ
              value: "Europe/Zurich"
          volumeMounts:
            - mountPath: /config/
              name: config
            - mountPath: /addons/
              name: plex
              subPath: addons/
            - mountPath: /movies/
              name: plex
              subPath: Movies/
          ports:
            - name: radarr
              containerPort: 7878
          livenessProbe:
            httpGet:
              path: /login
              port: radarr
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /login
              port: radarr
      terminationGracePeriodSeconds: 60
      volumes:
        - name: plex
          persistentVolumeClaim:
            claimName: plex-data
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
