apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: '*'
    helm:
      values: |
        envFromSecret: grafana
        env:
          GF_SERVER_ENABLE_GZIP: true
          GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: true
          GF_SECURITY_COOKIE_SECURE: true
          GF_ALERTING_ENABLED: false
          GF_AUTH_BASIC_ENABLED: false
          GF_AUTH_DISABLE_LOGIN_FORM: true
          GF_SERVER_ROOT_URL: https://grafana.srueg.ch
          GF_AUTH_GENERIC_OAUTH_ENABLED: true
          GF_AUTH_GENERIC_OAUTH_NAME: Keycloak
          GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: true
          GF_AUTH_GENERIC_OAUTH_CLIENT_ID: grafana
          GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://sso.srueg.ch/auth/realms/lab/protocol/openid-connect/auth
          GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://sso.srueg.ch/auth/realms/lab/protocol/openid-connect/token
          GF_AUTH_GENERIC_OAUTH_API_URL: https://sso.srueg.ch/auth/realms/lab/protocol/openid-connect/userinfo
          GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email roles
          GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: roles[0]
        ingress:
          enabled: true
          hosts:
          - grafana.srueg.ch
          tls:
          - hosts:
            - grafana.srueg.ch
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Loki
              type: loki
              url: http://loki-stack.loki:3100
              access: proxy
              isDefault: false
        admin:
          existingSecret: grafana
        rbac:
          namespaced: true
        sidecar:
          dashboards:
            enabled: true
            label: grafana_dashboard
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgBdPJcdEsvzYgSl0MuqDwTstzxDo27sqD0MAB92OG3fYfjf1DqxvVbOjZREnWiKs1SG6jSWYEN4Hp1Ggfgi8ClXfXZTqHUUzPuGVDFGdTRg8GFsrVvKn3ya44juUCUdHjPzfkn2mBQ4DyEwJrJSpenqXV/e0E5zkTDqnyGYW88h9Do7HGpp8tmZvyKKgK2HwULGY6yV4E1TL88jvVrwHtypv5DEfTdkhqSgvvMUegVvZH3OwY/cd9nVte619us6uIxHIe/kC2LMNOpa/DJYK5ymBbnxjiBU6TiP3nQZL/mFQcZYbfpEmk7dKE6Gj7dAi/8n6Bz/KT4hLxIxDW9QC0ISXtpKUuY1nU0nBedWDEgXz7mnaI9kv/psvFVFjIpCsc1hFPp4/anqEJFwGAUcVZ/IRf6SGz3eJz7XlUCt40iLE1BmsjNJfdksZ7+J1kTUtMDQU48X2cBJEBvCUdo6YoCmVY/d15upUyC93L6v+Na1AtQ2dbQwAPwXMyK3HyScLMBPBv6v1tHoUCIG92mevWT8GK5WzwUr+Mt5BsWJ2056I1JI/oEnqdU0g0f9w3NdovtO/6mLyGgVaWo5IZY9dn2/NgsapMC5Gqc+ViMy0SmO1BFAEbWf+W+807dtvgYmX19AWTBPohAFQBb+J0BlljdS/BOYTbKRLmYfBc5AP8fY9+oVirfL4FygMOjQyb/MTREkqu1Yz4/Mub/3NkGWrOYIZzrkIbsimkXAOSIHnB3jog9kPdY=
    admin-password: AgCs8TlznrWdFnITp8g7RVb1ca8GoTMmvHv2ukZ2DBsCfY1JP/1WpPcWhRK8kbmdxRk9V7Y5A9RSSzXrVA9a9Fqo0ly0DOs8bR8OX/3lIOhUqbF2kAzy8wKQ8lIHALP4iBoivqjn/Kf6z+8IdeK5FjGGgjEQCtHRULjOi8luCI7IDUYJ0SpR1gSF1j4asD8UyWdfIGxMnomZoFO1m1wfsiyj6/c61OaZIHSt6qXMNK3ZAjR80pAAk/TYKEOVujmwbyPIWJ7SgXnTyEGXvW8x06P8qxpXflomDq5cpotT9WKzNO5SWSg/QGFR+tqzclLVO2AJNQY4td29uZOh/mGQ5nQuuCBs+DDXPbO3vdPBBmSi2QuPfoV1PZbSajadCR81/xoWT/y92+JTknMSymMBpsCx0xRER0wrw3Mua47tlVRMGbHIaNDb02kYZoTMi8dOLDv+fOQKh/fQvzUf34vNtTrOpCNESTHIox1F/n9awqYQsRRQXf85xPUWzOf1BF+T9gKOaxYLYpSaGOQDOdXKYEugSmaiT3FTUW+S8Yn6ohu/4sreR8NeOYUKOFxor6/xVLi8qHduKP2pzLdjtYcF8NVPL/dL51MSqzaZMRjLcRRtbxLwbfvmB0sx2x4P7GU6XniX9PhzlX3GHaBrbJX0G3CFs/ucac1UsC2KRzo/TV/1QCQhhgALS3GaK9bh3Jym57q9H9Ly9c8Hz7LGGBfXR7oSot9TXaf4rYr7/HRxiOipZQ==
    admin-user: AgBLO+ToI4vA0kegnfOmgDrs5FcCoz7XraLhH/eH/4IoAWRCvX8pveXyEu76Xb5IXSICcuYuHlE1GEzncmav1nu3un32a1Qq/GFk8OpoBRqs3mjmrsq9JJrf+K0qHjVjcnoEooqLFF4VfK3wQnJu0jD4WMZVnm+EbxO+39a2T/nIb1NtqYlihxmqCT/3B51IgouCC+tZD7xDvhvSwBahMBrvzqlJStQmhtF3aCtiSC/NPGkop7mMIdLLrg2+0VjKIQrAYPayTC608e9KXZQADxOobjyUNhAMBg1RI0xZtoo++tRQgaMqyd2kNjz8awVFCbMb6SsKGb3WNuwOQf/aknP+ozGfkMW6MeOAooJPO+M6vo7VERattLRiq+QWQ/p1+GURbCwvG1FeO6wrdphOh3n0/PkJfG8zyVHdKqn4IN12Z8FLqRT4YiK7M4+AsVbv8M1rhkvc8hROteX0HzbNfYmmwv+szjGPO2f6JIDli7hJ+G976FAWuquiitkUTiF9WuRmKivuRFdZlArCcWLssQjaaOZHWh//+D3lmGnRMrL1dBiocQy70bmiMYqYHYLBp9WpISnJl0y6sd0bC2u8GvB7K3AfE/WrReb+HyGXL4A0Z4SjpiR1icnFQZoCS4nayK0LJxYU/yWhe1FLAaSa0jF/xOEpgFVWIEfK3FKn9pT4pyA1BuGdGwNhiXpkD/qr8oagqbpdmg==
  template:
    metadata:
      name: grafana
      namespace: monitoring
