apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: timemachine
  namespace: timemachine
spec:
  encryptedData:
    password: AgBun0k6mMrzenkW6utCA6Lt7RcGtUN10H7sN7GDnS0y3kKDLCscMEOmE9XIQj+3q1lOBCQgBN1JAsxlmdrSbS6Tnis4qpC2rAmM+y5yIirAMjSHf7L0cF9GEWwpujwbjAEF1LNBmk6Ynygm96OAxndHo2x6gRvzP9FN4q0paGGdyAM4dnddfu0F7AeueJthZ2MMnSVptavljufGb7Ttem+1vqlQpMfAahykl16/Q6z7Iepe2jvlzSAAmBkHbUo8e6XLAfc5wDKXJUjp4AtDA6d3tfbkGueDvDd3lHyL4aaqNL1koRyJmOEIUjDNLJDGjhnR4pwLZDLPbxDIVa2xOXxGX15rs6/VpV1C6V1reTu1xj+SdozmffsEvf3cBcdtx9o3PNoJ3K5cWR5l3OAjkRbikScF7SP48czDVVMZUlAVU5upqZwxK1gA4aXMjQgWieFmfTZrsMUICPsxgqejfa3WCQKpaCuEgqgm1AHJc9WQkYxhrj+XT90EdcoIQyoht3ij8RypPjR1KWfaC+etJUiP95QfH/ayFMX0X22kOxTTXlnqlezp9de0Xwf2dncGtqVdvdbXI8H800/edOjFOFBzo/ZeGKHdtx0I0yHwxA3qkymmA3opEewUr0XEYMq0DpH9E8xp5JuJBNvjJO7ugJtuJsDXbU3wW/p1xRVlmypw3yhufP3J2w0V2K9lXGlsq+bQbE57xLTvqcZzvk+WZ29D0MpQXCVRkZuE3vUplBB0tA==
  template:
    metadata:
      creationTimestamp: null
      name: timemachine
      namespace: timemachine
