apiVersion: v1
kind: Service
metadata:
  name: timemachine
  namespace: timemachine
  labels:
    app.kubernetes.io/name: timemachine
spec:
  type: NodePort
  ports:
  - name: smb
    port: 445
    targetPort: smb
    nodePort: 30445
  selector:
    app.kubernetes.io/name: timemachine
