apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data
  namespace: plex
  labels:
    app.kubernetes.io/name: plex
    app.kubernetes.io/instance: plex
spec:
  storageClassName: zfs
  resources:
    requests:
      storage: 100Gi
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      usage: plex-data
