apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  namespace: plex
  labels:
    app.kubernetes.io/name: plex
    app.kubernetes.io/instance: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
      app.kubernetes.io/instance: plex
  serviceName: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex
        app.kubernetes.io/instance: plex
    spec:
      containers:
      - name: plex
        image: docker.io/plexinc/pms-docker:1.23.2.4656-85f0adf5b@sha256:75f3edf65f709a2cb8f4c57f3dcd89a742f64f9a32a8d53afe8e08b61c84862e
        imagePullPolicy: IfNotPresent
        env:
        - name: PLEX_UID
          value: "10001"
        - name: PLEX_GID
          value: "10001"
        - name: TZ
          value: Europe/Zurich
        - name: ADVERTISE_IP
          value: https://plex.srueg.ch
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data
          name: data
          mountPropagation: HostToContainer
        - mountPath: /transcode
          name: transcode
        ports:
        - name: http
          containerPort: 32400
        livenessProbe:
          httpGet:
            path: /identity
            port: http
          initialDelaySeconds: 100
        readinessProbe:
          httpGet:
            path: /identity
            port: http
      terminationGracePeriodSeconds: 60
      volumes:
      - name: transcode
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: plex-data
      - name: config
        persistentVolumeClaim:
          claimName: plex-config
