apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  namespace: plex
  labels:
    app.kubernetes.io/name: plex
    app.kubernetes.io/instance: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
      app.kubernetes.io/instance: plex
  serviceName: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex
        app.kubernetes.io/instance: plex
    spec:
      containers:
      - name: plex
        image: docker.io/plexinc/pms-docker:1.22.3.4392-d7c624def@sha256:2a0287ad436492c33a84a41fb143227b01f33a1ec3408de5ac084f2add38122a
        imagePullPolicy: IfNotPresent
        env:
        - name: PLEX_UID
          value: "10001"
        - name: PLEX_GID
          value: "10001"
        - name: TZ
          value: Europe/Zurich
        - name: ADVERTISE_IP
          value: https://plex.srueg.ch
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data
          name: data
        - mountPath: /transcode
          name: transcode
        ports:
        - name: http
          containerPort: 32400
        livenessProbe:
          httpGet:
            path: /identity
            port: http
          initialDelaySeconds: 100
        readinessProbe:
          httpGet:
            path: /identity
            port: http
      terminationGracePeriodSeconds: 60
      volumes:
      - name: transcode
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: plex-data
      - name: config
        persistentVolumeClaim:
          claimName: plex-config
