apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calibre
  namespace: calibre
  labels:
    app.kubernetes.io/name: calibre
    app.kubernetes.io/instance: calibre
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: calibre
      app.kubernetes.io/instance: calibre
  serviceName: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calibre
        app.kubernetes.io/instance: calibre
    spec:
      containers:
      - name: calibre
        image: docker.io/linuxserver/calibre-web:0.6.11-ls110@sha256:ec3b94260d1af94670a6c8c70d1fe21a0c2abfa2a02c35b8a9a44b41639b30f6
        imagePullPolicy: IfNotPresent
        env:
        - name: PUID
          value: "10001"
        - name: PGID
          value: "10001"
        - name: TZ
          value: Europe/Zurich
        - name: DOCKER_MODS
          value: linuxserver/calibre-web:calibre
        volumeMounts:
        - mountPath: /config
          name: data
        ports:
        - name: http
          containerPort: 8083
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 300
        readinessProbe:
          httpGet:
            path: /
            port: http
      enableServiceLinks: false
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: calibre
