apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calibre
  namespace: calibre
  labels:
    app.kubernetes.io/name: calibre
    app.kubernetes.io/instance: calibre
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: calibre
      app.kubernetes.io/instance: calibre
  serviceName: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calibre
        app.kubernetes.io/instance: calibre
    spec:
      containers:
      - name: calibre
        image: docker.io/linuxserver/calibre-web:0.6.12-ls124@sha256:e4a44f67491e2cf895cd2e517c1f35698a9b27930e4346c9b60b823e4e21d3ec
        imagePullPolicy: IfNotPresent
        env:
        - name: PUID
          value: "10001"
        - name: PGID
          value: "10001"
        - name: TZ
          value: Europe/Zurich
        - name: DOCKER_MODS
          value: linuxserver/calibre-web:calibre
        volumeMounts:
        - mountPath: /config
          name: data
        ports:
        - name: http
          containerPort: 8083
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 300
        readinessProbe:
          httpGet:
            path: /
            port: http
      enableServiceLinks: false
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: calibre
