apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transmission
  namespace: plex
  labels:
    app.kubernetes.io/name: transmission
    app.kubernetes.io/instance: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: transmission
      app.kubernetes.io/instance: transmission
  serviceName: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: transmission
        app.kubernetes.io/instance: transmission
    spec:
      containers:
        - name: gatekeeper
          image: quay.io/keycloak/keycloak-gatekeeper:10.0.0
          imagePullPolicy: IfNotPresent
          args:
          - --listen=:3000
          - --discovery-url=https://sso.srueg.ch/auth/realms/lab
          - --client-id=transmission
          - --upstream-url=http://localhost:9091
          - --resources
          - "uri=/*|roles=transmission:login"
          - --enable-encrypted-token
          - --force-encrypted-cookie
          - --enable-logging
          - --enable-refresh-tokens
          env:
          - name: PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: transmission-gatekeeper
                key: client-secret
          - name: PROXY_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: transmission-gatekeeper
                key: encryption-key
          ports:
          - name: http
            containerPort: 3000
          livenessProbe:
            httpGet:
              path: /oauth/health
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /oauth/health
              port: http
        - name: transmission
          image: docker.io/linuxserver/transmission:3.00-r0-ls61
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "10001"
            - name: PGID
              value: "10001"
            - name: TZ
              value: "Europe/Zurich"
            - name: TRANSMISSION_WEB_HOME
              value: "/combustion-release/"
          volumeMounts:
            - mountPath: /config/
              name: config
              subPath: config/
            - mountPath: /watch/
              name: config
              subPath: watch/
            - mountPath: /downloads/
              name: plex
              subPath: addons/transmission/
          ports:
            - name: transmission
              containerPort: 9091
          livenessProbe:
            httpGet:
              path: /transmission/web/
              port: transmission
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /transmission/web/
              port: transmission
      terminationGracePeriodSeconds: 60
      volumes:
        - name: plex
          persistentVolumeClaim:
            claimName: plex-data
        - name: config
          persistentVolumeClaim:
            claimName: transmission-config
