apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: zfs-scrub-tank
  namespace: utils
  labels:
    cronjob: zfs-scrub-tank
spec:
  schedule: "0 3 1,14 * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            cronjob: zfs-scrub-tank
        spec:
          containers:
          - name: zfs-scrub
            image: quay.io/srueg/zfs-utils:v0.3.0
            imagePullPolicy: Always
            command: ["zpool", "scrub", "tank"]
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /dev/zfs
              name: zfs-device
          volumes:
          - name: zfs-device
            hostPath:
              path: /dev/zfs
          restartPolicy: OnFailure
