apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: argocd
spec:
  destination:
    namespace: netdata
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/netdata/helmchart.git
    path: charts/netdata
    targetRevision: master
    helm:
      values: |
        parent:
          env:
            DO_NOT_TRACK: "1"
          database:
            persistence: false
          alarms:
            persistence: false
        child:
          env:
            DO_NOT_TRACK: "1"
          persistUniqueID: false
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
          path: /
          hosts:
          - stats.srueg.ch
          tls:
          - hosts:
            - stats.srueg.ch
