apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-proxy
  namespace: netdata
  labels:
    app: oauth-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth-proxy
  template:
    metadata:
      labels:
        app: oauth-proxy
    spec:
      containers:
      - name: oauth-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1@sha256:791aef35b8d1d2a325028b188d5a650605d69985a0dab1233c06079e7321eee0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4180
          name: proxy
        args:
        - --http-address=:4180
        - --https-address=
        - --provider=keycloak
        - --keycloak-group=/admin
        - --email-domain=*
        - --scope=openid profile email
        - --login-url=https://sso.srueg.ch/auth/realms/lab/protocol/openid-connect/auth
        - --redeem-url=https://sso.srueg.ch/auth/realms/lab/protocol/openid-connect/token
        - --validate-url=https://sso.srueg.ch/auth/realms/lab/protocol/openid-connect/userinfo
        - --upstream=file:///dev/null
        - --reverse-proxy
        - --silence-ping-logging
        - --cookie-expire=1h
        - --skip-provider-button
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: netdata
        - name: OAUTH2_PROXY_COOKIE_SAMESITE
          value: lax
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-config
              key: client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-config
              key: cookie-secret
        livenessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /ping
            port: proxy
        readinessProbe:
          httpGet:
            path: /ping
            port: proxy
