apiVersion: v1
kind: ConfigMap
metadata:
  name: wg0-conf
  namespace: vpn
  labels:
    app: wireguard
data:
  wg0.conf: |
    [Interface]
    # PublicKey vTTVl0b3DN2bA1ufjqOXqeEorYGo3rH3p06GrKd6uwc=
    Address = 10.1.30.1/24,fdb0:5dfe:70d8:7f0b::1/48
    ListenPort = 51820
    PostUp = wg set %i private-key /etc/wireguard/wg0.key
    PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    MTU = 1500
    SaveConfig = false

    [Peer]
    # iMac
    PublicKey = sYko5QdPHfZkfeR+E9PI0rJqA2R0nsNLDTSb0wuKcjg=
    AllowedIPs = 10.1.30.3/32,fdb0:5dfe:70d8:7f0b::3/128

    [Peer]
    # Pixel2
    PublicKey = eZ1cez7MvoxtvbNsfCdogDIH7CE1Ewf55IifajWY5mM=
    AllowedIPs = 10.1.30.4/32,fdb0:5dfe:70d8:7f0b::4/128

    [Peer]
    # MacBook M.
    PublicKey = JIK3nSmGIOJR2ZqYtguBj1Ev0+WNiOjfFUBXKWZc+00=
    AllowedIPs = 10.1.30.5/32,fdb0:5dfe:70d8:7f0b::5/128
