apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: '*'
    helm:
      values: |
        installCRDs: true
        dex:
          enabled: false
        configs:
          secret:
            createSecret: false
        server:
          resources:
            limits:
              cpu: 200m
          extraArgs:
          - --insecure
          config:
            url: https://argocd.srueg.ch
            admin.enabled: 'false'
            oidc.config: |
              name: Keycloak
              issuer: https://sso.srueg.ch/auth/realms/lab
              clientID: argocd
              clientSecret: $oidc.keycloak.clientSecret
              requestedScopes: ["openid", "profile", "email"]
          rbacConfig:
            policy.default: role:readonly
            policy.csv: |
              g, admin, role:admin
          ingress:
            enabled: true
            hosts: [argocd.srueg.ch]
            tls:
            - hosts:
              - argocd.srueg.ch
        controller:
          extraArgs:
          - --app-resync
          - '60'
          resources:
            limits:
              cpu: 500m
        repoServer:
          resources:
            limits:
              cpu: 500m
        redis:
          resources:
            limits:
              cpu: 200m
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.keycloak.clientSecret: AgC04QoEjep2iMv5GTZoLauWLsx/pnQTzYtuuQ/Jrq2zof2fLOoMOphXpntLIVrCOeu93F028O+nFKlwnULGEFUlx39n4hINzEveEY6ZBr60/nCwWCJP14WAt89vQ2HDwCg2dwSLsUwPcTSmaVQQXwen27vqziaC1h2XHXH58zE8cGwpA4QZS5I5N55b+ZqNX3Uxvzi9KBplcCq420Vy36bZLBF+fw9vf37Qn3y44g5avU9Nck9/36n8NX1sKyTMWZD84t++C1c4Ne5OIBbg72cyeDxU65OGTTDwW5mN4ZiaSNAQIsfdxV8w7QVaLy4areDHULvyeuSX1Z57rDu80hSnEf+sFkX/5m4pqO/Up1ExB0bf758JJczaziUzR+/Hn1w5WusRHoHPvPT/SuO38AC/VqMGCBxBhucGlhP+dux5zULUHXp0OmZrumKWaeLLqyB++h2WcgzfQRdl50Xe7ycgIdF8mAsZcdHW8cpawpdsdnDmBne3xZiydoHVCDUBWV5KyYQkh1ePFpshCKHXIAYoJS1q2UenmIFGFIZ734QWImiNqMwwUUmhfA+xPcH8e+H4rC1bF3Sa66IgFZQChPr9/QXQhHU7Zhj5+beMc6DJ4ydYBH7hev41soVmhwAlAvBqsvLQjnXT96n5YRAZaPke10HFMnH3CFjJx8C2XstSh8pbpnna0kJ+I/ozwoUOL8kw0TqkKmLQLf2CMJL/XqeCsJ7KBGIr2P6vB7Of+2vlKicMpkA=
    server.secretkey: AgA9LGPg4mYtg0338sQqVrDsN248ocgGTu2P2TUv9cSS/ypJGwpn0MCbtv1KUO/8c5sOm/MrFNLQHOfDkMs0DZf1OsoJ/zd4mIZoXuEGf8pF/frUav0V04rbyiuXiLQGbqamzv9SLMZL6fJhWwaD2ho0WTbcyIttqeaqESSoKXZq9ogx+ucZYLEc8Ywao57uknjOQWsx2P+orRxciYvY/ZKnEiNDZVYC1XzApq1jALqEbJltTwne8YC7ShAXTTI6dhNYj0/9mR3zVbQvKHHecjLH9YM3IqxmNDRLJcezBaqxteOgul2pqqBqndYRRdP5egDxYGXk3/eytsrwssA3B080567TQjoVVlgGY6Z3En7PhRXggKRcS6LsGsYSBN2sdRJnowKVyVwg8JMpRqmj5PaJ4t4XO24TgUZC7OvE052KRAa7DyX6LZb8Xx+/MX0al5Zr2oTbaHj2eZc/tnIPj9dL1npVNIzpLhwXBWxFneXII1GTQ4/0XKORezcRDJ+E+vhOJRZaO+oykIBrqb9dsUGY6FBWU+9b7irf2LjVtjJ/m5ea0Eeu/E3wTDldNA9l04ac8q9xg7M7mOuG6jS3jU4InkTJErLApr1tLfnqPkuY65atkWXYojGffBmbGiOunkEqTcxDQma0/UfBKqEscSuPzfvJNuesDg9xzutAgh0vjPnnBPjnnug+6gos+BSv9xVMz0w+FlQBUoxthTPp30IUVBd8PhUZou7C3tSkPDS0udtKROO1qq3wIvwbOA==
  template:
    metadata:
      creationTimestamp: null
      name: argocd-secret
      namespace: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  description: Default Project
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  orphanedResources:
    warn: false
