apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://codecentric.github.io/helm-charts
    chart: keycloak
    targetRevision: '*'
    helm:
      values: |
        replicas: 2
        affinity: ""
        extraEnv: |
          - name: KEYCLOAK_USER
            value: keycloak
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak
                key: password
          - name: JAVA_OPTS
            value: >-
              -XX:+UseContainerSupport
              -XX:MaxRAMPercentage=50.0
              -Dkeycloak.profile.feature.account_api=enabled
              -Dkeycloak.profile.feature.account2=enabled
              -Djava.net.preferIPv4Stack=true
              -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS
              -Djava.awt.headless=true
          - name: JGROUPS_DISCOVERY_PROTOCOL
            value: dns.DNS_PING
          - name: JGROUPS_DISCOVERY_PROPERTIES
            value: 'dns_query={{ include "keycloak.serviceDnsName" . }}'
          - name: CACHE_OWNERS_COUNT
            value: "2"
          - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
            value: "2"
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
          - name: KEYCLOAK_STATISTICS
            value: all
        ingress:
          enabled: true
          rules:
          - host: sso.srueg.ch
            paths: ["/"]
          tls:
          - hosts:
            - sso.srueg.ch
            secretName: ""
        resources:
          limits:
            memory: 512Mi
        imagePullSecrets: []

        postgresql:
          enabled: true
          persistence:
            enabled: true
            existingClaim: keycloak-postgresql
          existingSecret: keycloak-postgresql
---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak
  namespace: keycloak
spec:
  encryptedData:
    password: AgCwWIVsqLaqkHc7Ao1nmsk2dQKgDIsxwkQX3Fhb9zVmg/1EXHy9tbFh4bbuj5ve9ChiEVjSqbbATcwixkT8WMiym+yIvBn2FP+LmG1mjQR5tVpXeg+15aenghEnlsF11ovrIbUDiPTpjARcGtDMCTcO8S0R5vz11HbjOp8haxpFlI6bBlnX3/P7dDnK4iUspf7R0F5C57SMZ9/K/IEXvqgcDrxiL3neGPdgU43ASwLfudFpemCKu5Y1yJRat+EprTR3bb/cNkSJEjgHQqKr4oATEwN8VVDQMFZ3gxbWnlhJaYv5Z/YXhGRWu8lmUk2WwbZ4cEECyhp39kB6dFdnDeefrkZ1A+Cr+y5t//j5rZ1EFzUQdbw4pOAwp9U6zno/PuEZUSrspwmbrCUkSrnXNRbK9SqYgweQbG7x2AY7WXokqTqbbiAqmUugkq1CJslhidzw3St6bonKufPZa/8qJQKWmzfDEKVSw4jEIL/+FQWi/jm+0kIERMJaN2Uv/9UtfFYv9c7ig7R9iozVBbEY4M7T1SwQJeWzVdIVHrxUX/Ea3wqGc4YofdYXb2VKUlaUzvCiOmGo9Q/g3g1BsDwO6qktL6HHn03qtyaBMjOHItOb6u40ZjMqxVixiXFYa1wo18ZcH3mimhaDXwBJHz8LvPk5vrC0wsj012yYXUKTJdZzYtenLplE9lNbeGqQfeg4rNTlH9QvdEJFicrWs7QBnoSTHwOsiH61lzQuG09rteMwig==
  template:
    metadata:
      name: keycloak
      namespace: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-postgres-password: AgB8UCdRnpbfY8FAtHzbuSupdZ0l9jSfpvRVna7CBECIy7ig1ypOEAjKRt1TklEuVRnRlGZ1Ed0eG6gGjyp5Yv9HdHTrIFQvbdY8y4tDs8k3RREhJ1baIXkqKyHevMlNQSxfn+8615oyYDYx1eYzxepYxu9Xl6UbLErJuOh6C7zyb/K8VjDOvmgWgs/w9KHIggLh4FySUKP8LTy0Z2+Da2IWGvt1mIiH24zO3TUBfoVoSWDJkokZcE9ovMTGwh5ctAkpXE6bIS1DcXaNXBDQ+GwFj6YJYkOAHMT2u/upCnpLHW/E/lFYhPpIvt+DzV6AxGASRFVSPWbUmYhive4grTEDIlEStilrWqlxZdB5I9tuaFT2MXsUXZBpfMmfYmAw32HsEka7bXxRx93cXVFWU0RNsfBI+ri1Vj09X5usNfOyb74bWCQtrcWXnn22pAVQQYyq92GMbOX2QWPjM4cAcu1Z17TISRQxY36REirivHPuXEkbYZxPj/17d+AHC00upT+N/ODl66EatUF60rbH8ssxWWeU15rgdjBnksN0X0K0OtiHPVqVh/+yENpG3+nuzmbOFhOI8PWyzLIbvTBJO9u+iBz8xTXUu6+9V3dLjo1cL/pP49ho1DIKxuMRHb+XH30H4XfopjQlwdfoc9scSx4PJsxnvr1j5qkdtO6mEpxZdjlfWNp/daeb1W6qUftCOCVMP9a5SSDiSqDsFeQcYzXbbTX2wzphrndYjJi6wcywaQ==
  template:
    metadata:
      name: keycloak-postgresql
      namespace: keycloak
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgresql
  namespace: keycloak
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: zfs
  selector:
    matchLabels:
      usage: keycloak
