apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://codecentric.github.io/helm-charts
    chart: keycloak
    targetRevision: '9.*'
    helm:
      values: |
        replicas: 2
        affinity: ""
        extraEnv: |
          - name: KEYCLOAK_USER
            value: keycloak
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak
                key: password
          - name: JAVA_OPTS
            value: >-
              -XX:+UseContainerSupport
              -XX:MaxRAMPercentage=50.0
              -Dkeycloak.profile.feature.account_api=enabled
              -Dkeycloak.profile.feature.account2=enabled
        ingress:
          enabled: true
          rules:
          - host: sso.srueg.ch
          tls:
          - hosts:
            - sso.srueg.ch
            secretName: ""
        resources:
          limits:
            memory: 512Mi

        postgresql:
          enabled: true
          persistence:
            enabled: true
            size: 1Gi
            storageClass: zfs
          existingSecret: keycloak-postgresql
---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak
  namespace: keycloak
spec:
  encryptedData:
    password: AgBDzV2pokhfK6AEmWNB5uOMZfJrrFbm8jbs0mMnaVFDmaLeqRtKB+C2WZ18KLYRzksW3cHhtJLcqej4thLDj6TxOnVeiChMsZqC25dAh/hy1WX0Xht2+1316DgmT2YMLp28YsBDZ0lhve5iJb/OLIbaCvWFPbU0VcAIJepmhbma/AoFDQ1nG6LIs1ZjGKJFcZ4A2p1bhqDd8yvK3Sld4wCfruDaye0hscznofOwLUac5q71JNlNGBPxgEKY7ezq788WWz8GsY+zsuWRiq1jB6RvseotxfswePSUjOOe5xEdLTF0z7WzbZcP6rSZiFQ2MV9rmUD3ziwewcJHhMB1NrXq4nNLD2bkcHL28dQ3phyFWcZJEseN0/Y/HvuxapPfaWJ17T7V3SMHOk4WFTmc+o2nw6NQCECHBEu2oyiPBRZmRnJH+Q/YKEq5IXUMEC9bssx6o+L2uy5wG7F+AIZDi2luERsTs98lWZmLwmuQk9wz9tMKjCtZShrN3TF2xPfRd7wyNPCX4N80enWYLrGvv+sF5V/hNhR8ZGL/+FRwBJrdXO42pmkhhWbFu/U2stpwthYC6DBVlmj7UGSnh94njOrZMakf3LVI3Mp8CQibaaMdjraRJdAAGK6Ui6xShjofFZnliv/TgkbCtx6Vgdc5WX6fUArnUo3xBgzJmu/osK9rKFNyipYKKhin2KjzFTCMiXByyNCVPJqtXDSGZ8oMnjdoiz8gK2TESuSvXgZKuTyXHg==
  template:
    metadata:
      name: keycloak
      namespace: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-postgresql
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgA/1eHo03A1hlgv8RZsY6UgMwEU2Qlf5V6m/l3v1khZ529p3jXHKLfiw6SwYaPaZkfOLnnmDABgOXXer230dK4Ozl3fQCZTcy/QqdTI9NIEhkuf6kvENYmXe1lG05VNw042fzqhTudxqLIbZCa6V+JCKUWvkbqXjHEXDz8Iu7inEz25Ke8rIxnoEAeZdLPXgUecYbYQP9WQJgw6ObmdinugFtLnFmL2rPMZ/QVrg0tfa81iGYnBun57+depp57AWBT2mjQrEupViFXXM4xo0qQX9PulBr1SsejrvujarZtbj6B+hzgGVGEyrU+YzqhAQUpw1GvomHVMD9uXUviW7wwHcHiCigLwVAGOwZyXMznC5C1PbQwM58+Cf1+bNO/abo2TrdqyhjJEDZfkmRYYqKqdh8Z6FM13h5of0RYIZSbZllG8fVFUdmM42R2uWlVtRDAevhSP3wTon19+X0vdhdUmQra2h0D1thYEFNip9vZ7oJ5+QYNl5t83+en6vcGIExqK2w0ZL2G/guQjbgkFEZmrBWD2eUegdjmYaRH1bhM40XhyW3JErV3MUrKoURYUANuPdqC7sJkgtFCjorEpJykFYA0YgOG8V2/ICKP2BBv/wJU5IermcugEjB+BkrM9llnrbP807Q/PUVglRfQZJxfnWkHfBaBRqW76NqRM6Q+ey+s0bCyMV7m27JUiqoRkdn5vWs20sZjaUqYJ4JMB6H9xMQjUoerTYX+uy9r4HYPMNA==
  template:
    metadata:
      name: keycloak-postgresql
      namespace: keycloak
