apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.helm.sh/stable
    chart: sealed-secrets
    targetRevision: '*'
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
