apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timemachine
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: timemachine
    server: https://kubernetes.default.svc
  project: default
  source:
    path: timemachine
    repoURL: https://github.com/srueg/gitops-redkeep.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
